#!/bin/bash
ldap_db_path=/opt/zimbra/data/ldap/mdb/db/data.mdb

if [ -f "${ldap_db_path}" ]; then
    echo "${ldap_db_path} exists. Skipping LDAP backup restore"
    chown zimbra:zimbra /home/zimbra
    chown zimbra:zimbra /opt/zimbra/.
    chown zimbra:zimbra /opt/zimbra/.*
    echo "Starting services"
    sudo -i -u zimbra zmcontrol start
else
    echo "Restoring LDAP database from backup"
    sudo -i -u zimbra /bin/bash -c "/opt/zimbra/common/sbin/slapadd -q -b '' -F '/opt/zimbra/data/ldap/config' -l '/opt/zimbra/data/ldap/mdb/db/ldap.bak'"
    echo "Starting services"
    sudo -i -u zimbra zmcontrol start
    /bin/bash /zimbra/update-zimbra
fi

echo "Starting ssh service..."
/usr/sbin/service ssh start

echo "Starting STAF service..."
/usr/local/staf/startSTAFProc.sh >/opt/zimbra/log/staf.log 2>&1 &
sleep 10
/usr/local/staf/bin/STAF local service add service LOG LIBRARY STAFLog
/usr/local/staf/bin/STAF local TRUST SET MACHINE '*' LEVEL 5

echo "STARTUP COMPLETE"
/bin/sleep infinity
