#!/bin/bash

echo "Updating the hostname in /etc/hosts file..."
cp /etc/hosts ~/hosts.new
sed -i '$d' ~/hosts.new
echo `tail -n 1 /etc/hosts | cut -f 1` "    zcs-dev.test zcs-dev" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new

ldap_db_path=/opt/zimbra/data/ldap/mdb/db/data.mdb

if [ -f "${ldap_db_path}" ]; then
    echo "${ldap_db_path} exists. Skipping LDAP backup restore"
    chown zimbra:zimbra /home/zimbra
    chown zimbra:zimbra /opt/zimbra/.
    chown zimbra:zimbra /opt/zimbra/.*
    echo "Starting services"
    sudo -i -u zimbra zmcontrol start
else
    echo "Restoring LDAP database from backup"
    sudo -i -u zimbra /bin/bash -c "/opt/zimbra/common/sbin/slapadd -q -b '' -F '/opt/zimbra/data/ldap/config' -l '/opt/zimbra/data/ldap/mdb/db/ldap.bak'"
    echo "Starting services"
    sudo -i -u zimbra zmcontrol start
    /bin/bash /zimbra/update-zimbra
fi

echo "Starting ssh service..."
/usr/sbin/service ssh start

echo "STARTUP COMPLETE"
/bin/sleep infinity
