#!/bin/bash
# Do this after a ZCS install to fix necessary permissions
# Expects the following environment variables to be set. These are used to
# update the information in the .gitconfig file that is laid down.
# * GITEMAIL - The email address you use on github
# * GITNAME - Your first and last name.

DN=$(dirname $0)

echo "Performing updates for development"
chown zimbra:zimbra /home/zimbra
chown zimbra:zimbra /opt/zimbra/.
chown zimbra:zimbra /opt/zimbra/.*
chmod -R o+w /opt/zimbra/lib/
chmod -R o+w /opt/zimbra/jetty/
chmod -R o+w /opt/zimbra/common/etc/openldap/schema
chmod o+w /opt/zimbra/conf/zimbra.ldif
chmod +w /opt/zimbra/conf/attrs/zimbra-attrs.xml
chmod -R o+w /opt/zimbra/common/etc/openldap/zimbra
cp ${DN}/junit-4.8.2.jar  /opt/zimbra/jetty/webapps/service/WEB-INF/lib/.
echo "zimbra:zimbra" | chpasswd
echo "Allow unauthenticated PINGs. This is required by the SOAP-Harness tests"
sudo -i -u zimbra zmlocalconfig -e allow_unauthed_ping=true
echo "Enable mailbox debugging"
/zimbra/enable-debug.sh
echo "Enabling local mail delivery"
sudo -i -u zimbra zmprov mcf zimbraMtaLmtpHostLookup native
echo "Restarting mailbox"
sudo -i -u zimbra zmmailboxdctl restart

OZ=${DN}/opt-zimbra
for f in $(ls ${OZ})
do
    F=${OZ}/${f}
    if [ "$f" = "DOT-ssh" ]
    then
		for f2 in ${F}/*; do
			if [ $(basename $f2) = "authorized_keys" ]; then
				cat ${f2} >> /opt/zimbra/.ssh/authorized_keys
			else
				cp ${f2} /opt/zimbra/.ssh/
			fi
		done

        chown zimbra /opt/zimbra/.ssh/*
		chmod 600 /opt/zimbra/.ssh/*
    fi

    if [ -f "${F}" ]
    then
        F2=".$(echo ${f} | tr -d 'DOT-')"
        cp "${F}" "/opt/zimbra/${F2}"
        chown zimbra "/opt/zimbra/${F2}"
    fi
done

sed -i.bak "s/GITEMAIL/${GITEMAIL}/" /opt/zimbra/.gitconfig
sed -i.bak "s/GITNAME/${GITNAME}/" /opt/zimbra/.gitconfig

